name: Build and Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use the Temurin distribution
          java-version: '17'      # Set the Java version to 17

      - name: Install dependencies
        run: npm install --force

      - name: Build Android
        run: |
          java -version   # Verify Java version
          npm run android:bundle:release

      - name: Upload ABB for upload
        uses: actions/upload-artifact@v4
        with:
          name: android_abb
          path: "./android/app/build/outputs/bundle/release/app-release.aab"

      - name: Upload Android App Bundle to Google Play Store
        id: upload_aab
        uses: KevinRohn/github-action-upload-play-store@v1.0.0
        with:
          service_account_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          package_name: "com.flipdigitals.cardvest"
          aab_file_path: "./android/app/build/outputs/bundle/release/app-release.aab"
          track: "internal"
          release_status: "completed"

  deploy-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby v3.1.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies with Bundler
        run: bundle install

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install xcodes
        run: sudo gem install xcode-install

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.4'

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'  # Specify the Xcode version you want to use

      - name: Show available Xcode versions
        run: xcodebuild -showsdks

      - name: Install npm dependencies
        run: npm install --force

      - name: Install CocoaPods Dependencies
        run: bundle exec pod install --project-directory=ios/

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Create App Store Connect API Key file
        run: |
          echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}" > fastlane/AuthKey_3D4ADG3459.p8

      - name: Set up Match for certificates
        run: bundle exec fastlane match adhoc --readonly
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - name: Deploy to TestFlight
        run: bundle exec fastlane ios deploy_testflight_production
        env:
          APP_STORE_CONNECT_EMAIL: ${{ secrets.APP_STORE_CONNECT_EMAIL }}
          APP_STORE_CONNECT_API_KEY_PATH: ${{ secrets.APP_STORE_CONNECT_API_KEY_PATH }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - name: Upload IPA for upload
        uses: actions/upload-artifact@v4
        with:
          name: ios_ipa
          path: "./Cardvest.app.dSYM.zip"

