name: Build and Deploy

on:
  pull_request:
    branches:
    - main
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install --force

      - name: Build Android
        run: |
          java -version
          yarn android:bundle:release

      - name: Upload ABB for upload
        uses: actions/upload-artifact@v4
        with:
          name: android_abb
          path: "./android/app/build/outputs/bundle/release/app-release.aab"

      - name: Upload Android App Bundle to Google Play Store
        id: upload_aab
        uses: KevinRohn/github-action-upload-play-store@v1.0.0
        with:
          service_account_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          package_name: "com.flipdigitals.cardvest"
          aab_file_path: "./build/outputs/bundle/release/app-release.aab"
          track: "internal"
          release_status: "draft"

  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install --force

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios
          pod install --repo-update

      - name: Build iOS
        run: |
          xcodebuild -workspace Cardvest.xcworkspace \
            -scheme Cardvest \
            -sdk iphoneos \
            -configuration Release \
            archive \
            -archivePath $PWD/build/Cardvest.xcarchive
          xcodebuild -exportArchive \
            -archivePath $PWD/build/Cardvest.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $PWD/build

  deploy-ios:
    needs: build-ios
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Fastlane
        run: sudo gem install fastlane

      - name: Upload to TestFlighttou
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        run: |
          cd ios
          fastlane pilot upload --ipa ../build/Cardvest.ipa
